/********************************************************************************
*					Tangram Library - version 8.0								*
*********************************************************************************
* Copyright (C) 2002-2015 by Tangram Team.   All Rights Reserved.				*
*
* THIS SOURCE FILE IS THE PROPERTY OF TANGRAM TEAM AND IS NOT TO
* BE RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE EXPRESSED
* WRITTEN CONSENT OF TANGRAM TEAM.
*
* THIS SOURCE CODE CAN ONLY BE USED UNDER THE TERMS AND CONDITIONS
* OUTLINED IN THE GPL LICENSE AGREEMENT.TANGRAM TEAM
* GRANTS TO YOU (ONE SOFTWARE DEVELOPER) THE LIMITED RIGHT TO USE
* THIS SOFTWARE ON A SINGLE COMPUTER.
*
* CONTACT INFORMATION:
* mailto:sunhui@tangramfx.com
* http://www.tangramFX.com
*
*
********************************************************************************/
package com.tangram;

/**
 * thrown in util.cpp
 */
public class WrongThreadException extends JacobException {
	/**
	 * identifier generated by Eclipse
	 */
	private static final long serialVersionUID = 6308780364980228692L;

	/**
	 * standard 0 arg constructor with no message
	 * 
	 */
	public WrongThreadException() {
		super("No Message Provided.");
	}

	/**
	 * standard constructor with a string message
	 * 
	 * @param s
	 */
	public WrongThreadException(String s) {
		super(s);
	}
}